- hosts: intercoms
  remote_user: pi

  vars:
    install_dir: /home/pi/intercompy
    config_dir: /home/pi/.config/intercompy
    state_dir: /home/pi/.local/state/intercompy

  tasks:
    - name: install packages
      become: true
      apt:
        name: '{{ packages }}'
        state: latest
      async: 3600
      poll: 5
      vars:
        packages:
          - python3-pip
          - python3-setuptools
          - python3-wheel
          - python3-venv
          - python3-pygame # Keyboard GPIO simulation
          - python3-rpi.gpio # Pin / button listening, LED feedback, etc.
          - python3-ruamel.yaml # Configuration
          - python3-click # Command-line args
          - python3-pyaudio # Audio recording
          - build-essential
          - flac
          - ffmpeg # Audio recording
          - vlc # Audio playback
      tags:
        - never
        - first
        - update

    - name: setup intercompy directories
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        owner: pi
        group: pi
        mode: '0755'
      loop:
        - "{{install_dir}}"
        - "{{install_dir}}/intercompy"
        - "{{config_dir}}"
        - "{{state_dir}}"
      tags:
        - never
        - first
        - update
        - code

    - name: copy setup.py
      ansible.builtin.copy:
        src: "{{playbook_dir}}/../{{item}}"
        dest: "{{install_dir}}/{{item}}"
        owner: pi
        group: pi
        mode: '0644'
        directory_mode: '0755'
      loop:
        - setup.py
        - requirements.in.txt
      tags:
        - never
        - first
        - update
        - code
      notify:
        - restart intercompy

    - name: copy module files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{install_dir}}/intercompy/"
        owner: pi
        group: pi
        mode: '0644'
        directory_mode: '0755'
      with_fileglob:
        - "{{playbook_dir}}/../intercompy/*.py"
      tags:
        - never
        - first
        - update
        - code
      notify:
        - restart intercompy

    - name: install pyrogram and tgcrypto
      become: true
      ansible.builtin.pip:
        name: "{{ item }}"
      async: 3600
      poll: 5
      tags:
        - never
        - first
        - update
      loop:
        - pyrogram
        - tgcrypto

    - name: install intercompy
      ansible.builtin.pip:
        chdir: "{{install_dir}}"
        virtualenv: "{{install_dir}}/venv"
        virtualenv_site_packages: yes
        virtualenv_command: "/usr/bin/python3 -m venv --system-site-packages"
        name: 'file://{{install_dir}}'
      async: 3600
      poll: 5
      tags:
        - never
        - first
        - update
        - code
      notify:
        - restart intercompy

    - name: install configuration
      ansible.builtin.template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: pi
        group: pi
        mode: '0600'
      tags:
        - never
        - first
        - config
      loop:
        - src: templates/config.yaml.j2
          dest: "{{config_dir}}/config.yaml"
      notify:
        - restart intercompy

    - name: install Alsa configuration
      ansible.builtin.template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: pi
        group: pi
        mode: '0600'
      tags:
        - never
        - first
        - config
      when: "config_alsa|bool|default(false)"
      loop:
        - src: templates/asoundrc.j2
          dest: "/home/pi/.asoundrc"
      notify:
        - restart intercompy

    - name: install systemd service
      become: true
      ansible.builtin.template:
        src: templates/intercompy.service.j2
        dest: "/etc/systemd/system/intercompy.service"
        owner: root
        group: root
        mode: '0644'
      tags:
        - never
        - first
        - update
        - code
      notify:
        - restart intercompy

  handlers:
    - name: restart intercompy
      become: true
      ansible.builtin.systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: intercompy
